# Generated by Django 4.2.6 on 2023-11-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonLog',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('examinee_name', models.CharField(max_length=20)),
                ('examinee_no', models.CharField(max_length=20)),
                ('existing_photo', models.CharField(max_length=300)),
                ('new_photo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'comparison_log',
            },
        ),
    ]
